server:
 port: 8760

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://localhost:8760/eureka/

spring:
 application:
  name: eureka-server